apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/smodak-rh/example-rok-libecpg-1?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "master"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: example-packages
    appstudio.openshift.io/component: subrata-sample-rpm-package-onboarding
    pipelines.appstudio.openshift.io/type: build
  name: subrata-sample-rpm-package-onboarding-on-push
  namespace: test-rhtap-3000-tenant
spec:
  timeouts:
    pipeline: "6h"
  params:
    - name: package-name
      value: libecpg
    - name: git-url
      value: "{{ source_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: target-branch
      value: "main"
    - name: build-platforms
      value:
        - localhost
        - linux/arm64
        - linux/ppc64le
        - linux/s390x
        - linux/amd64
    - name: build-architectures
      value:
        - x86_64
    - name: ociStorage
      value: quay.io/redhat-user-workloads-stage/test-rhtap-3000-tenant/subrata-sample-rpm-package-onboarding:on-pr-{{revision}}
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/konflux-ci/rpmbuild-pipeline.git
      - name: revision
        value: "main"
      - name: pathInRepo
        value: pipeline/build-rpm-package.yaml
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
  taskRunTemplate:
    serviceAccountName: build-pipeline-subrata-sample-rpm-package-onboarding
